---

- hosts: all
  sudo: yes

  pre_tasks:
    - name: add Google public key to apt
      apt_key:
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: add Google to apt-get repositories
      apt_repository:
        repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - apt: "name={{ item }} state=installed update_cache=yes"
      with_items:
        - dbus-x11
        - default-jre
        - firefox
        - git
        - google-chrome-stable
        - nodejs
        - npm
        - python
        - xvfb

  tasks:
    - name: symlink /user/bin/nodejs to /usr/bin/node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link

    - name: install bower
      command: npm install -g bower

    - name: install web-component-tester
      command: npm install -g web-component-tester

    - name: copy xvfb init script to /etc/init.d
      template:
        src: "{{ playbook_dir }}/templates/xvfb"
        dest: /etc/init.d/xvfb
        mode: 0770

    - name: Start xvfb service
      service:
        name: xvfb
        state: started
